# Generated by Django 2.0.1 on 2018-01-14 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PlayersManagement', '0002_player_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gamenumber', models.IntegerField(null=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('category', models.CharField(choices=[('BB', 'Baseball'), ('501', '501')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamescoring.GameNumber')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlayersManagement.Player')),
            ],
        ),
    ]
