# Generated by Django 2.0.1 on 2018-01-17 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamescoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='rank',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participant',
            name='score',
            field=models.IntegerField(null=True),
        ),
    ]
